name: Maven deploy
on:
  workflow_dispatch:

jobs:
  container-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: actions/setup-java@v2
        with:
          distribution: 'liberica'
          java-version: '8'
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B deploy
      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "ActionDeploy"
      - name: Create Tag
        run: |
          cver=$(grep -o "<version[^>]*>[^<]*</version>" pom.xml | head -n 1 | sed -e "s/<version>\(.*\)<\/version>/\1/")
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag -a v${cver} -m 'version '${cver}
          echo "ReleaseTag=v"${cver} >> $GITHUB_ENV
          afiles=$(find . -path "*/docs/*/"${cver}"/*"${cver}"*.jar" | tr "\n" ",")
          echo "ReleaseFile="${afiles/%?/} >> $GITHUB_ENV
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          ArtifactErrorsFailBuild: true
          artifacts: ${{ env.ReleaseFile }}
          tag: ${{ env.ReleaseTag }}
          token: ${{ secrets.GITHUB_TOKEN }}