name: Maven deploy
on:
  workflow_dispatch:

jobs:
  container-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: actions/setup-java@v2
        with:
          distribution: 'liberica'
          java-version: '8'
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B deploy
      - name: Create Tag
        run: ./gittag.sh
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "/doc/*.jar"
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "ActionDeploy"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main